a = int(input("Введите первое число: "))
b = int(input("Введите второе число: "))
c = int(input("Введите третье число: "))
mx = (a if (a >= b and a >= c) else (b if (b >= a and b >= c) else c))
print("Максимальное значение:", mx)
