# Generated by Django 4.2.2 on 2023-09-28 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратная связь'},
        ),
    ]
